/*
* SPDX-FileCopyrightText: Copyright 2022 | Regione Piemonte
* SPDX-License-Identifier: EUPL-1.2
*/
/**
 * Prodis
 * API per il backend della suite di Prodis.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { ApiError } from '../model/apiError';
import { DecodificaGenerica } from '../model/decodificaGenerica';
import { Ruolo } from '../model/ruolo';
import { UserAccessLog } from '../model/userAccessLog';


import { Configuration }                                     from '../configuration';


export interface CommonServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;
    

    /**
    * 
    * Restituisce la data calcolata.
    * @param dataInput valore della data.
    * @param numeroGiorniLavorativi numero di giorni lavorativi da aggiungere
    */
    getDataCalcolataConGiorniLavorativi(dataInput: string, numeroGiorniLavorativi: number, extraHttpRequestParams?: any): Observable<Date>;

    /**
    * 
    * Restituisce il parametro.
    * @param nomeParametro Nome del Parametro.
    */
    getParametro(nomeParametro: string, extraHttpRequestParams?: any): Observable<DecodificaGenerica>;

    /**
    * 
    * Restituisce dati registrati su sistema.
    */
    getRuolo(extraHttpRequestParams?: any): Observable<Array<Ruolo>>;

    /**
    * 
    * Inserisce info su tabella di log per accesso.
    * @param loUserLog 
    */
    insertUserAccessLog(loUserLog: UserAccessLog, extraHttpRequestParams?: any): Observable<UserAccessLog>;

}
