/*
* SPDX-FileCopyrightText: Copyright 2022 | Regione Piemonte
* SPDX-License-Identifier: EUPL-1.2
*/
/**
 * Prodis
 * API per il backend della suite di Prodis.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { ApiError } from '../model/apiError';
import { CategorieEscluse } from '../model/categorieEscluse';
import { DatiProvinciali } from '../model/datiProvinciali';
import { ElencoProvScoperture } from '../model/elencoProvScoperture';
import { LavoratoriInForza } from '../model/lavoratoriInForza';
import { PartTime } from '../model/partTime';
import { ProspettoProvincia } from '../model/prospettoProvincia';
import { ProvIntermittenti } from '../model/provIntermittenti';
import { VistaElencoProvQ2 } from '../model/vistaElencoProvQ2';


import { Configuration }                                     from '../configuration';


export interface DatiProvincialiServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;
    

    /**
    * 
    * Restituisce dati registrati su sistema.
    * @param idCategorieEscluse L&#39;id della CategoriaEsclusa da eliminare.
    */
    deleteCategorieEscluse(idCategorieEscluse: number, extraHttpRequestParams?: any): Observable<{}>;

    /**
    * 
    * Elimina DatiProvinciali con l&#39;idProspettoProv passato come parametro.
    * @param idProspettoProv L&#39;idProspettoProv.
    */
    deleteDatiProvinciali(idProspettoProv: number, extraHttpRequestParams?: any): Observable<boolean>;

    /**
    * 
    * Elimina intermittente su sistema.
    * @param idIntermittenti L&#39;idIntermittenti.
    */
    deleteIntermittenti(idIntermittenti: number, extraHttpRequestParams?: any): Observable<{}>;

    /**
    * 
    * Elimina dati registrati su sistema.
    * @param idLavoratoriInForza idLavoratoriInForza del LavoratoreInForza da eliminare.
    */
    deleteLavoratoriInForza(idLavoratoriInForza: number, extraHttpRequestParams?: any): Observable<LavoratoriInForza>;

    /**
    * 
    * Elimina dato registrato su sistema.
    * @param idPartTime id idPartTime da eliminare sul db.
    */
    deletePartTime(idPartTime: number, extraHttpRequestParams?: any): Observable<PartTime>;

    /**
    * 
    * download xls dei lavoratori in forza di tutte le province di del prospetto con idProspetto.
    * @param idProspetto 
    */
    downloadProspettoLavoratoriInForza(idProspetto: number, extraHttpRequestParams?: any): Observable<Blob>;

    /**
    * 
    * download xls dei lavoratori in forza per una specifica provincia.
    * @param idProspettoProv 
    */
    downloadProvinciaLavoratoriInForza(idProspettoProv: number, extraHttpRequestParams?: any): Observable<Blob>;

    /**
    * 
    * Restituisce dati registrati su sistema.
    * @param idProspettoProv L&#39;idProspettoProv.
    */
    getCategorieEscluseByIdProspettoProv(idProspettoProv: number, extraHttpRequestParams?: any): Observable<Array<CategorieEscluse>>;

    /**
    * 
    * Restituisce true se il passaggio dal Q2 al Q3.
    * @param idProspetto L&#39;id del prospetto.
    */
    getConfermaProvince(idProspetto: number, extraHttpRequestParams?: any): Observable<{}>;

    /**
    * 
    * Restituisce dati registrati su sistema.
    * @param idProspettoProv L&#39;idProspettoProv.
    */
    getDatiProvincialiByIdProspettoProv(idProspettoProv: number, extraHttpRequestParams?: any): Observable<DatiProvinciali>;

    /**
    * 
    * Restituisce la lista di VistaElencoProvQ2 registrati su sistema.
    * @param idProspetto L&#39;idProspetto.
    */
    getElencoProvinceQ2ByIdProspetto(idProspetto: number, extraHttpRequestParams?: any): Observable<Array<VistaElencoProvQ2>>;

    /**
    * 
    * Restituisce elenco scoperture provinciali
    * @param idProspetto L&#39;idProspetto.
    */
    getElencoScopertureByIdProspetto(idProspetto: number, extraHttpRequestParams?: any): Observable<Array<ElencoProvScoperture>>;

    /**
    * 
    * Restituisce dati registrati su sistema.
    * @param idProspettoProv L&#39;idProspettoProv.
    */
    getLavoratoriInForzaByIdProspettoProv(idProspettoProv: number, extraHttpRequestParams?: any): Observable<Array<LavoratoriInForza>>;

    /**
    * 
    * Restituisce dati registrati su sistema.
    * @param idProspettoProv L&#39;idProspettoProv.
    */
    getPartTimeByIdProspettoProv(idProspettoProv: number, extraHttpRequestParams?: any): Observable<Array<PartTime>>;

    /**
    * 
    * Restituisce dati registrati su sistema.
    * @param idProspettoProv L&#39;idProspettoProv.
    */
    getProvIntermittentiByIdProspettoProv(idProspettoProv: number, extraHttpRequestParams?: any): Observable<Array<ProvIntermittenti>>;

    /**
    * 
    * Restituisce dati registrati su sistema.
    * @param idProspetto L&#39;idProspetto.
    */
    getRiepilogoByIdProspetto(idProspetto: number, extraHttpRequestParams?: any): Observable<Array<ProspettoProvincia>>;

    /**
    * 
    * Restituisce dati registrati su sistema.
    * @param idDatiProvinciali L&#39;id DatiProvinciali.
    * @param categorieEscluse 
    */
    postCategorieEscluse(idDatiProvinciali: number, categorieEscluse: CategorieEscluse, extraHttpRequestParams?: any): Observable<{}>;

    /**
    * 
    * Restituisce dati registrati su sistema.
    * @param prospettoProvincia 
    */
    postDatiProvinciali(prospettoProvincia: ProspettoProvincia, extraHttpRequestParams?: any): Observable<{}>;

    /**
    * 
    * Restituisce dati registrati su sistema.
    * @param idDatiProvinciali L&#39;idDatiProvinciali.
    * @param intermittenti 
    * @param idPartTime L&#39;idPartTime se e solo se si sta modificando un part time in un intermittente.
    */
    postIntermittenti(idDatiProvinciali: number, intermittenti: ProvIntermittenti, idPartTime?: number, extraHttpRequestParams?: any): Observable<{}>;

    /**
    * 
    * Restituisce dati registrati su sistema.
    * @param idDatiProvinciali flag per continuare col salvataggio in caso di warning.
    * @param flagWarning idDatiProvinciali di cui il LavoratoreInForza da salvare è associato.
    * @param lavoratoriInForza 
    */
    postLavoratoriInForza(idDatiProvinciali: number, flagWarning: boolean, lavoratoriInForza: LavoratoriInForza, extraHttpRequestParams?: any): Observable<LavoratoriInForza>;

    /**
    * 
    * Restituisce dati registrati su sistema.
    * @param idDatiProvinciali L&#39;idDatiProvinciali.
    * @param PartTime 
    * @param idIntermittenti L&#39;idIntermittenti valorizzato se e solo se si sta modificando un intermittente in un part time.
    */
    postPartTime(idDatiProvinciali: number, PartTime: PartTime, idIntermittenti?: number, extraHttpRequestParams?: any): Observable<{}>;

    /**
    * 
    * Restituisce dati registrati su sistema.
    * @param idDatiProvinciali L&#39;id DatiProvinciali.
    * @param idCategorieEscluse L&#39;id CategorieEscluse.
    * @param categorieEscluse 
    */
    putCategorieEscluse(idDatiProvinciali: number, idCategorieEscluse: number, categorieEscluse: CategorieEscluse, extraHttpRequestParams?: any): Observable<{}>;

    /**
    * 
    * Restituisce dati registrati su sistema.
    * @param idProspettoProv idProspettoProv da modificare.
    * @param flagBozza 
    * @param datiProvinciali 
    */
    putDatiProvinciali(idProspettoProv: number, flagBozza: boolean, datiProvinciali: DatiProvinciali, extraHttpRequestParams?: any): Observable<DatiProvinciali>;

    /**
    * 
    * Restituisce dati registrati su sistema.
    * @param idDatiProvinciali id DatiProvinciali.
    * @param idIntermittenti id ProvIntermittenti da modificare.
    * @param intermittenti 
    */
    putIntermittenti(idDatiProvinciali: number, idIntermittenti: number, intermittenti: ProvIntermittenti, extraHttpRequestParams?: any): Observable<ProvIntermittenti>;

    /**
    * 
    * Restituisce dati registrati su sistema.
    * @param flagWarning flag per continuare col salvataggio in caso di warning.
    * @param idDatiProvinciali idDatiProvinciali di cui il LavoratoreInForza da salvare è associato.
    * @param idLavoratoriInForza idLavoratoriInForza del LavoratoreInForza da salvare è associato.
    * @param lavoratoriInForza 
    */
    putLavoratoriInForza(flagWarning: boolean, idDatiProvinciali: number, idLavoratoriInForza: number, lavoratoriInForza: LavoratoriInForza, extraHttpRequestParams?: any): Observable<LavoratoriInForza>;

    /**
    * 
    * Restituisce dati registrati su sistema.
    * @param idDatiProvinciali id DatiProvinciali.
    * @param idPartTime id idPartTime da modificare.
    * @param PartTime 
    */
    putPartTime(idDatiProvinciali: number, idPartTime: number, PartTime: PartTime, extraHttpRequestParams?: any): Observable<PartTime>;

    /**
    * 
    * inserisce lavoratori da file per il prospetto con idProspetto
    * @param idProspetto 
    * @param attachment 
    */
    uploadProspettoLavoratoriInForza(idProspetto?: string, attachment?: Blob, extraHttpRequestParams?: any): Observable<Blob>;

    /**
    * 
    * inserisce lavoratori da file per la provincia con idProspettoProv
    * @param idProspettoProv 
    * @param attachment 
    */
    uploadProvinciaLavoratoriInForza(idProspettoProv?: string, attachment?: Blob, extraHttpRequestParams?: any): Observable<Blob>;

}
