/*
* SPDX-FileCopyrightText: Copyright 2022 | Regione Piemonte
* SPDX-License-Identifier: EUPL-1.2
*/
/**
 * Prodis
 * API per il backend della suite di Prodis.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { ApiError } from '../model/apiError';
import { Atecofin } from '../model/atecofin';
import { Ccnl } from '../model/ccnl';
import { Comune } from '../model/comune';
import { DecodificaGenerica } from '../model/decodificaGenerica';
import { Provincia } from '../model/provincia';
import { StatoProspetto } from '../model/statoProspetto';


import { Configuration }                                     from '../configuration';


export interface DecodificaServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;
    

    /**
    * 
    * Restituisce dati registrati su sistema.
    */
    getAtecofin(extraHttpRequestParams?: any): Observable<Array<Atecofin>>;

    /**
    * 
    * Restituisce dati registrati su sistema.
    */
    getCcnl(extraHttpRequestParams?: any): Observable<Array<Ccnl>>;

    /**
    * 
    * Restituisce dati registrati su sistema.
    * @param idProvincia idProvincia
    * @param codComuneMin codComuneMin
    * @param dsProTComune dsProTComune
    * @param data data
    */
    getComune(idProvincia?: number, codComuneMin?: string, dsProTComune?: string, data?: Date, extraHttpRequestParams?: any): Observable<Array<Comune>>;

    /**
    * 
    * Restituisce dati registrati su sistema.
    */
    getProvincia(extraHttpRequestParams?: any): Observable<Array<Provincia>>;

    /**
    * 
    * Restituisce dati registrati su sistema.
    */
    getStatoProspetto(extraHttpRequestParams?: any): Observable<Array<StatoProspetto>>;

    /**
    * 
    * Restituisce dati registrati su sistema.
    * @param filtro 
    */
    postAssunzioneProtettaDecodifica(filtro: DecodificaGenerica, extraHttpRequestParams?: any): Observable<Array<DecodificaGenerica>>;

    /**
    * 
    * Restituisce dati registrati su sistema.
    * @param filtro 
    */
    postAtecofinDecodifica(filtro: DecodificaGenerica, extraHttpRequestParams?: any): Observable<Array<DecodificaGenerica>>;

    /**
    * 
    * Restituisce dati registrati su sistema.
    * @param filtro 
    */
    postCategoriaEscluseDecodifica(filtro: DecodificaGenerica, extraHttpRequestParams?: any): Observable<Array<DecodificaGenerica>>;

    /**
    * 
    * Restituisce dati registrati su sistema.
    * @param filtro 
    */
    postCausaSospensioneDecodifica(filtro: DecodificaGenerica, extraHttpRequestParams?: any): Observable<Array<DecodificaGenerica>>;

    /**
    * 
    * Restituisce dati registrati su sistema.
    * @param filtro 
    */
    postCcnlDecodifica(filtro: DecodificaGenerica, extraHttpRequestParams?: any): Observable<Array<DecodificaGenerica>>;

    /**
    * 
    * Restituisce dati registrati su sistema.
    * @param filtro 
    */
    postComuneDecodifica(filtro: DecodificaGenerica, extraHttpRequestParams?: any): Observable<Array<DecodificaGenerica>>;

    /**
    * 
    * Restituisce dati registrati su sistema.
    * @param filtro 
    */
    postContrattiDecodifica(filtro: DecodificaGenerica, extraHttpRequestParams?: any): Observable<Array<DecodificaGenerica>>;

    /**
    * 
    * Restituisce dati registrati su sistema.
    * @param filtro 
    */
    postDichiaranteDecodifica(filtro: DecodificaGenerica, extraHttpRequestParams?: any): Observable<Array<DecodificaGenerica>>;

    /**
    * 
    * Restituisce dati registrati su sistema.
    * @param filtro 
    */
    postQualificaDecodifica(filtro: DecodificaGenerica, extraHttpRequestParams?: any): Observable<Array<DecodificaGenerica>>;

    /**
    * 
    * Restituisce dati registrati su sistema.
    * @param filtro 
    */
    postRegioneDecodifica(filtro: DecodificaGenerica, extraHttpRequestParams?: any): Observable<Array<DecodificaGenerica>>;

    /**
    * 
    * Restituisce dati registrati su sistema.
    * @param filtro 
    */
    postSoggettiDecodifica(filtro: DecodificaGenerica, extraHttpRequestParams?: any): Observable<Array<DecodificaGenerica>>;

    /**
    * 
    * Restituisce dati registrati su sistema.
    * @param filtro 
    */
    postStatiEsteriDecodifica(filtro: DecodificaGenerica, extraHttpRequestParams?: any): Observable<Array<DecodificaGenerica>>;

    /**
    * 
    * Restituisce dati registrati su sistema.
    * @param filtro 
    */
    postStatoConcessioneDecodifica(filtro: DecodificaGenerica, extraHttpRequestParams?: any): Observable<Array<DecodificaGenerica>>;

    /**
    * 
    * Restituisce dati registrati su sistema.
    * @param filtro 
    */
    postTipologiaLavoratoreDecodifica(filtro: DecodificaGenerica, extraHttpRequestParams?: any): Observable<Array<DecodificaGenerica>>;

}
