/*
* SPDX-FileCopyrightText: Copyright 2022 | Regione Piemonte
* SPDX-License-Identifier: EUPL-1.2
*/
/**
 * Prodis
 * API per il backend della suite di Prodis.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { ApiError } from '../model/apiError';
import { DatiAzienda } from '../model/datiAzienda';
import { LavoratoriSilp } from '../model/lavoratoriSilp';
import { SedeLegale } from '../model/sedeLegale';


import { Configuration }                                     from '../configuration';


export interface SilpServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;
    

    /**
    * 
    * Restituisce dati registrati su sistema.
    * @param codiceFiscale codiceFiscale
    */
    getAzienda(codiceFiscale: string, extraHttpRequestParams?: any): Observable<DatiAzienda>;

    /**
    * 
    * Restituisce dati registrati su sistema.
    * @param codiceFiscale codiceFiscale
    */
    getLavoratore(codiceFiscale: string, extraHttpRequestParams?: any): Observable<LavoratoriSilp>;

    /**
    * 
    * Restituisce dati registrati su sistema.
    * @param idAzienda idAzienda
    */
    getSedi(idAzienda: string, extraHttpRequestParams?: any): Observable<SedeLegale>;

}
