CREATE SEQUENCE SEQ_D_CATEGORIE_ESCLUSE
    START WITH 0
    INCREMENT BY 1
    MINVALUE 1
    MAXVALUE 1E27
    nocycle
    noorder;

CREATE SEQUENCE SEQ_D_IMPORT_ERRORI
    START WITH 0
    INCREMENT BY 1
    MINVALUE 1
    MAXVALUE 1E27
    nocycle
    noorder;

CREATE SEQUENCE SEQ_D_LAVORATORI_IN_FORZA
    START WITH 0
    INCREMENT BY 1
    MINVALUE 1
    MAXVALUE 1E27
    nocycle
    noorder;

CREATE SEQUENCE SEQ_D_PART_TIME
    START WITH 0
    INCREMENT BY 1
    MINVALUE 1
    MAXVALUE 1E27
    nocycle
    noorder;

CREATE SEQUENCE SEQ_D_PDF_SILP
    START WITH 0
    INCREMENT BY 1
    MINVALUE 0
    MAXVALUE 1E27
    nocycle
    noorder;

CREATE SEQUENCE SEQ_D_POSTI_LAVORO_DISP
    START WITH 0
    INCREMENT BY 1
    MINVALUE 1
    MAXVALUE 1E27
    nocycle
    noorder;

CREATE SEQUENCE SEQ_D_PROSPETTO
    START WITH 0
    INCREMENT BY 1
    MINVALUE 1
    MAXVALUE 1E27
    nocycle
    noorder;

CREATE SEQUENCE SEQ_D_PROV_COMPENSAZIONI
    START WITH 0
    INCREMENT BY 1
    MINVALUE 1
    MAXVALUE 1E27
    nocycle
    noorder;

CREATE SEQUENCE SEQ_D_PROV_INTERMITTENTI
    START WITH 0
    INCREMENT BY 1
    MINVALUE 1
    MAXVALUE 1E27
    nocycle
    noorder;

CREATE SEQUENCE SEQ_D_USER_ACCESS_LOG
    START WITH 0
    INCREMENT BY 1
    MINVALUE 1
    MAXVALUE 1E27
    nocycle
    noorder;

CREATE SEQUENCE SEQ_R_PROSPETTO_PROVINCIA
    START WITH 0
    INCREMENT BY 1
    MINVALUE 1
    MAXVALUE 1E27
    nocycle
    noorder;

