/* ---------------------------------------------------------------------- */
/* Add foreign key constraints                                            */
/* ---------------------------------------------------------------------- */

ALTER TABLE PRO_D_PROSPETTO_GRADUALITA ADD
    FOREIGN KEY (ID_PROSPETTO) REFERENCES PRO_D_PROSPETTO (ID_PROSPETTO);

ALTER TABLE PRO_D_SEDE_LEGALE ADD
    FOREIGN KEY (ID_T_COMUNE) REFERENCES PRO_T_COMUNE (ID_T_COMUNE);

ALTER TABLE PRO_D_SEDE_LEGALE ADD
    FOREIGN KEY (ID_T_STATI_ESTERI) REFERENCES PRO_T_STATI_ESTERI (ID_T_STATI_ESTERI);

ALTER TABLE PRO_D_SEDE_LEGALE ADD
    FOREIGN KEY (ID_PROSPETTO) REFERENCES PRO_D_DATI_AZIENDA (ID_PROSPETTO);

ALTER TABLE PRO_D_PROV_SOSPENSIONE ADD
    FOREIGN KEY (ID_PROSPETTO_PROV) REFERENCES PRO_D_DATI_PROVINCIALI (ID_PROSPETTO_PROV);

ALTER TABLE PRO_D_PROV_SOSPENSIONE ADD
    FOREIGN KEY (ID_T_CAUSA_SOSPENSIONE) REFERENCES PRO_T_CAUSA_SOSPENSIONE (ID_T_CAUSA_SOSPENSIONE);

ALTER TABLE PRO_D_PROV_SOSPENSIONE ADD
    FOREIGN KEY (ID_T_STATO_CONCESSIONE) REFERENCES PRO_T_STATO_CONCESSIONE (ID_T_STATO_CONCESSIONE);

ALTER TABLE PRO_D_CATEGORIE_ESCLUSE ADD
    FOREIGN KEY (ID_PROSPETTO_PROV) REFERENCES PRO_D_DATI_PROVINCIALI (ID_PROSPETTO_PROV);

ALTER TABLE PRO_D_CATEGORIE_ESCLUSE ADD
    FOREIGN KEY (ID_T_CATEGORIE_ESCLUSE) REFERENCES PRO_T_CATEGORIA_ESCLUSE (ID_T_CATEGORIA_ESCLUSE);

ALTER TABLE PRO_D_PART_TIME ADD
    FOREIGN KEY (ID_PROSPETTO_PROV) REFERENCES PRO_D_DATI_PROVINCIALI (ID_PROSPETTO_PROV);

ALTER TABLE PRO_D_PART_TIME ADD
    FOREIGN KEY (ID_TIPO_RIPROP_PT) REFERENCES PRO_T_TIPO_RIPROP_PT (ID_TIPO_RIPROP_PT);

ALTER TABLE PRO_D_PROV_ESONERO ADD
    FOREIGN KEY (ID_PROSPETTO_PROV) REFERENCES PRO_D_DATI_PROVINCIALI (ID_PROSPETTO_PROV);

ALTER TABLE PRO_D_PROV_ESONERO ADD
    FOREIGN KEY (ID_T_STATO_CONCESSIONE) REFERENCES PRO_T_STATO_CONCESSIONE (ID_T_STATO_CONCESSIONE);

ALTER TABLE PRO_D_PROV_COMPENSAZIONI ADD
    FOREIGN KEY (ID_T_STATO_CONCESSIONE) REFERENCES PRO_T_STATO_CONCESSIONE (ID_T_STATO_CONCESSIONE);

ALTER TABLE PRO_D_PROV_COMPENSAZIONI ADD
    FOREIGN KEY (ID_T_PROVINCIA_COMP) REFERENCES PRO_T_PROVINCIA (ID_T_PROVINCIA);

ALTER TABLE PRO_D_PROV_COMPENSAZIONI ADD
    FOREIGN KEY (ID_PROSPETTO_PROV) REFERENCES PRO_D_DATI_PROVINCIALI (ID_PROSPETTO_PROV);

ALTER TABLE PRO_D_RIEPILOGO_PROVINCIALE ADD
    FOREIGN KEY (ID_PROSPETTO_PROV) REFERENCES PRO_R_PROSPETTO_PROVINCIA (ID_PROSPETTO_PROV);

ALTER TABLE PRO_D_PROSPETTO ADD
    FOREIGN KEY (ID_T_STATO_PROSPETTO) REFERENCES PRO_T_STATO_PROSPETTO (ID_T_STATO_PROSPETTO);

ALTER TABLE PRO_D_PROSPETTO ADD
    FOREIGN KEY (ID_PROSPETTO_PRECEDENTE) REFERENCES PRO_D_PROSPETTO (ID_PROSPETTO);

ALTER TABLE PRO_D_PROSPETTO ADD
    FOREIGN KEY (ID_T_SOGGETTI) REFERENCES PRO_T_SOGGETTI (ID_T_SOGGETTI);

ALTER TABLE PRO_D_PROSPETTO ADD
    FOREIGN KEY (ID_T_STATO_VERIFICA) REFERENCES PRO_T_STATO_VERIFICA (ID_T_STATO_VERIFICA);

ALTER TABLE PRO_D_PROSPETTO ADD
    FOREIGN KEY (ID_T_COMUNICAZIONE) REFERENCES PRO_T_COMUNICAZIONE (ID_T_COMUNICAZIONE);

ALTER TABLE PRO_D_PROSPETTO ADD
    FOREIGN KEY (ID_T_CATEGORIA_AZIENDA) REFERENCES PRO_T_CATEGORIA_AZIENDA (ID_T_CATEGORIA_AZIENDA);

ALTER TABLE PRO_T_CCNL ADD
    FOREIGN KEY (ID_T_CCNL_PREV) REFERENCES PRO_T_CCNL (ID_T_CCNL);

ALTER TABLE PRO_R_PROSPETTO_PROVINCIA ADD
    FOREIGN KEY (ID_PROSPETTO) REFERENCES PRO_D_PROSPETTO (ID_PROSPETTO);

ALTER TABLE PRO_R_PROSPETTO_PROVINCIA ADD
    FOREIGN KEY (ID_T_PROVINCIA) REFERENCES PRO_T_PROVINCIA (ID_T_PROVINCIA);

ALTER TABLE PRO_T_COMUNE ADD
    FOREIGN KEY (ID_PROVINCIA) REFERENCES PRO_T_PROVINCIA (ID_T_PROVINCIA);

ALTER TABLE PRO_T_COMUNE ADD
    FOREIGN KEY (ID_T_CPI) REFERENCES PRO_T_CPI (ID_T_CPI);

ALTER TABLE PRO_D_PROV_CONVENZIONE ADD
    FOREIGN KEY (ID_PROSPETTO_PROV) REFERENCES PRO_D_DATI_PROVINCIALI (ID_PROSPETTO_PROV);

ALTER TABLE PRO_D_PROV_CONVENZIONE ADD
    FOREIGN KEY (ID_T_ASSUNZIONE_PROTETTA) REFERENCES PRO_T_ASSUNZIONE_PROTETTA (ID_T_ASSUNZIONE_PROTETTA);

ALTER TABLE PRO_D_PROV_CONVENZIONE ADD
    FOREIGN KEY (ID_T_STATO_CONCESSIONE) REFERENCES PRO_T_STATO_CONCESSIONE (ID_T_STATO_CONCESSIONE);

ALTER TABLE PRO_D_PROSPETTO_PROV_SEDE ADD
    FOREIGN KEY (ID_PROSPETTO_PROV) REFERENCES PRO_D_DATI_PROVINCIALI (ID_PROSPETTO_PROV);

ALTER TABLE PRO_D_PROSPETTO_PROV_SEDE ADD
    FOREIGN KEY (ID_T_COMUNE) REFERENCES PRO_T_COMUNE (ID_T_COMUNE);

ALTER TABLE PRO_D_PROV_INTERMITTENTI ADD
    FOREIGN KEY (ID_PROSPETTO_PROV) REFERENCES PRO_D_DATI_PROVINCIALI (ID_PROSPETTO_PROV);

ALTER TABLE PRO_D_PROV_GRADUALITA ADD
    FOREIGN KEY (ID_PROSPETTO_PROV) REFERENCES PRO_D_DATI_PROVINCIALI (ID_PROSPETTO_PROV);

ALTER TABLE PRO_D_DATI_AZIENDA ADD
    FOREIGN KEY (ID_T_COMUNE) REFERENCES PRO_T_COMUNE (ID_T_COMUNE);

ALTER TABLE PRO_D_DATI_AZIENDA ADD
    FOREIGN KEY (ID_T_ATECOFIN) REFERENCES PRO_T_ATECOFIN (ID_T_ATECOFIN);

ALTER TABLE PRO_D_DATI_AZIENDA ADD
    FOREIGN KEY (ID_PROSPETTO) REFERENCES PRO_D_PROSPETTO (ID_PROSPETTO);

ALTER TABLE PRO_D_DATI_AZIENDA ADD
    FOREIGN KEY (ID_T_DICHIARANTE) REFERENCES PRO_T_DICHIARANTE (ID_T_DICHIARANTE);

ALTER TABLE PRO_D_DATI_AZIENDA ADD
    FOREIGN KEY (ID_T_STATI_ESTERI) REFERENCES PRO_T_STATI_ESTERI (ID_T_STATI_ESTERI);

ALTER TABLE PRO_D_DATI_AZIENDA ADD
    FOREIGN KEY (ID_T_CCNL) REFERENCES PRO_T_CCNL (ID_T_CCNL);

ALTER TABLE PRO_D_RIEPILOGO_NAZIONALE ADD
    FOREIGN KEY (ID_PROSPETTO) REFERENCES PRO_D_PROSPETTO (ID_PROSPETTO);

ALTER TABLE PRO_T_PROVINCIA ADD
    FOREIGN KEY (ID_T_REGIONE) REFERENCES PRO_T_REGIONE (ID_T_REGIONE);

ALTER TABLE PRO_D_ASS_PUBBLICHE ADD
    FOREIGN KEY (ID_PROSPETTO) REFERENCES PRO_D_PROSPETTO (ID_PROSPETTO);

ALTER TABLE PRO_D_ASS_PUBBLICHE ADD
    FOREIGN KEY (ID_T_REGIONE) REFERENCES PRO_T_REGIONE (ID_T_REGIONE);

ALTER TABLE PRO_D_POSTI_LAVORO_DISP ADD
    FOREIGN KEY (ID_T_COMUNE_ASSUNZIONE) REFERENCES PRO_T_COMUNE (ID_T_COMUNE);

ALTER TABLE PRO_D_POSTI_LAVORO_DISP ADD
    FOREIGN KEY (ID_T_QUALIFICA_PROFESSI_ISTAT) REFERENCES PRO_T_ISTAT2001LIVELLO5 (ID_T_ISTAT2001LIVELLO5);

ALTER TABLE PRO_D_POSTI_LAVORO_DISP ADD
    FOREIGN KEY (ID_T_STATO_ESTERO_ASSUNZIONE) REFERENCES PRO_T_STATI_ESTERI (ID_T_STATI_ESTERI);

ALTER TABLE PRO_D_POSTI_LAVORO_DISP ADD
    FOREIGN KEY (ID_PROSPETTO_PROV) REFERENCES PRO_D_DATI_PROVINCIALI (ID_PROSPETTO_PROV);

ALTER TABLE PRO_D_LAVORATORI_IN_FORZA ADD
    FOREIGN KEY (ID_PROSPETTO_PROV) REFERENCES PRO_D_DATI_PROVINCIALI (ID_PROSPETTO_PROV);

ALTER TABLE PRO_D_LAVORATORI_IN_FORZA ADD
    FOREIGN KEY (ID_T_CONTRATTO) REFERENCES PRO_T_CONTRATTI (ID_T_CONTRATTO);

ALTER TABLE PRO_D_LAVORATORI_IN_FORZA ADD
    FOREIGN KEY (ID_T_STATO_ESTERO_NASCITA) REFERENCES PRO_T_STATI_ESTERI (ID_T_STATI_ESTERI);

ALTER TABLE PRO_D_LAVORATORI_IN_FORZA ADD
    FOREIGN KEY (ID_T_QUALIFICA_PROFESSIONALE_I) REFERENCES PRO_T_ISTAT2001LIVELLO5 (ID_T_ISTAT2001LIVELLO5);

ALTER TABLE PRO_D_LAVORATORI_IN_FORZA ADD
    FOREIGN KEY (ID_T_COMUNE_NASCITA) REFERENCES PRO_T_COMUNE (ID_T_COMUNE);

ALTER TABLE PRO_D_LAVORATORI_IN_FORZA ADD
    FOREIGN KEY (ID_T_ASSUNZIONE_PROTETTA) REFERENCES PRO_T_ASSUNZIONE_PROTETTA (ID_T_ASSUNZIONE_PROTETTA);

ALTER TABLE PRO_D_DATI_PROVINCIALI ADD
    FOREIGN KEY (ID_PROSPETTO_PROV) REFERENCES PRO_R_PROSPETTO_PROVINCIA (ID_PROSPETTO_PROV);

ALTER TABLE PRO_D_LAVORATORI_SILP ADD
    FOREIGN KEY (ID_T_PROVINCIA) REFERENCES PRO_T_PROVINCIA (ID_T_PROVINCIA);

ALTER TABLE PRO_D_LAVORATORI_SILP ADD
    FOREIGN KEY (ID_T_ASSUNZIONE_PROTETTA) REFERENCES PRO_T_ASSUNZIONE_PROTETTA (ID_T_ASSUNZIONE_PROTETTA);

ALTER TABLE PRO_D_LAVORATORI_SILP ADD
    FOREIGN KEY (ID_T_QUALIFICA_PROFESSIONALE_I) REFERENCES PRO_T_ISTAT2001LIVELLO5 (ID_T_ISTAT2001LIVELLO5);

ALTER TABLE PRO_D_LAVORATORI_SILP ADD
    FOREIGN KEY (ID_T_CONTRATTO) REFERENCES PRO_T_CONTRATTI (ID_T_CONTRATTO);

ALTER TABLE PRO_D_LAVORATORI_SILP ADD
    FOREIGN KEY (ID_T_COMUNE_NASCITA) REFERENCES PRO_T_COMUNE (ID_T_COMUNE);

ALTER TABLE PRO_D_LAVORATORI_SILP ADD
    FOREIGN KEY (ID_T_STATO_ESTERO_NASCITA) REFERENCES PRO_T_STATI_ESTERI (ID_T_STATI_ESTERI);

ALTER TABLE PRO_D_IMPORT_ERRORI ADD
    FOREIGN KEY (COD_ERRORE) REFERENCES PRO_T_IMPORT_ERRORI_SPICOM (COD_ERRORE);

ALTER TABLE PRO_D_PROV_ESONERO_AUTOCERT ADD
    FOREIGN KEY (ID_PROSPETTO_PROV) REFERENCES PRO_D_DATI_PROVINCIALI (ID_PROSPETTO_PROV);

ALTER TABLE PRO_D_PDF_PROSPETTO ADD
    FOREIGN KEY (ID_PROSPETTO) REFERENCES PRO_D_PROSPETTO (ID_PROSPETTO);

ALTER TABLE PRO_D_PDF_SILP ADD
    FOREIGN KEY (ID_T_PROVINCIA_PROT) REFERENCES PRO_T_PROVINCIA (ID_T_PROVINCIA);

