/*
* SPDX-FileCopyrightText: Copyright 2022 | Regione Piemonte
* SPDX-License-Identifier: EUPL-1.2
*/
/**
 * Prodis
 * API per il backend della suite di Prodis.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { AssPubblichePK } from './assPubblichePK';
import { Prospetto } from './prospetto';
import { Regione } from './regione';


export interface AssPubbliche { 
    codUserAggiorn?: string;
    codUserInserim?: string;
    dAggiorn?: Date;
    dInserim?: Date;
    dsNote?: string;
    id?: AssPubblichePK;
    prospetto?: Prospetto;
    regione?: Regione;
    saldoDisabili?: number;
    saldoExArt18?: number;
}
