/*
* SPDX-FileCopyrightText: Copyright 2022 | Regione Piemonte
* SPDX-License-Identifier: EUPL-1.2
*/
/**
 * Prodis
 * API per il backend della suite di Prodis.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { AssunzioneProtetta } from './assunzioneProtetta';
import { Comune } from './comune';
import { Contratti } from './contratti';
import { Istat2001livello5 } from './istat2001livello5';
import { LavoratoriSilpPK } from './lavoratoriSilpPK';
import { Provincia } from './provincia';
import { StatiEsteri } from './statiEsteri';


export interface LavoratoriSilp { 
    assunzioneProtetta?: AssunzioneProtetta;
    categoriaAssunzione?: string;
    categoriaSoggetto?: string;
    cognome?: string;
    comune?: Comune;
    contratti?: Contratti;
    dataFineRapporto?: Date;
    dataInizioRapporto?: Date;
    dataNascita?: Date;
    flgImportOnline?: string;
    id?: LavoratoriSilpPK;
    istat2001livello5?: Istat2001livello5;
    nome?: string;
    orarioSettContrattualeMin?: number;
    orarioSettPartTimeMin?: number;
    provincia?: Provincia;
    sesso?: string;
    statiEsteri?: StatiEsteri;
}
