/*
* SPDX-FileCopyrightText: Copyright 2022 | Regione Piemonte
* SPDX-License-Identifier: EUPL-1.2
*/
/**
 * Prodis
 * API per il backend della suite di Prodis.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { AssunzioneProtetta } from './assunzioneProtetta';
import { Comune } from './comune';
import { Contratti } from './contratti';
import { Istat2001livello5 } from './istat2001livello5';
import { StatiEsteri } from './statiEsteri';


export interface LavoratoriInForza { 
    assunzioneProtetta?: AssunzioneProtetta;
    categoriaAssunzione?: string;
    categoriaSoggetto?: string;
    codUserAggiorn?: string;
    codUserInserim?: string;
    codiceFiscale?: string;
    cognome?: string;
    comune?: Comune;
    contratti?: Contratti;
    dAggiorn?: Date;
    dInserim?: Date;
    dataFineRapporto?: Date;
    dataInizioRapporto?: Date;
    dataNascita?: Date;
    flgCompletato?: string;
    id?: number;
    idProspettoProv?: number;
    istat2001livello5?: Istat2001livello5;
    nome?: string;
    orarioSettContrattualeMin?: number;
    orarioSettPartTimeMin?: number;
    percentualeDisabilita?: number;
    sesso?: string;
    statiEsteri?: StatiEsteri;
}
