/*
* SPDX-FileCopyrightText: Copyright 2022 | Regione Piemonte
* SPDX-License-Identifier: EUPL-1.2
*/
/**
 * Prodis
 * API per il backend della suite di Prodis.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { DatiProvinciali } from './datiProvinciali';


export interface ProvEsoneroAutocert { 
    codUserAggiorn?: string;
    codUserInserim?: string;
    dAggiorn?: Date;
    dInserim?: Date;
    dataAutocert?: Date;
    datiProvinciali?: DatiProvinciali;
    id?: number;
    nLav60x1000?: number;
    nLavEsoneroAutocert?: number;
    percentualeEsAutocert?: number;
}
