/*
* SPDX-FileCopyrightText: Copyright 2022 | Regione Piemonte
* SPDX-License-Identifier: EUPL-1.2
*/
/**
 * Prodis
 * API per il backend della suite di Prodis.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface RiepilogoNazionale { 
    baseComputoArt18?: number;
    baseComputoArt3?: number;
    codUserAggiorn?: string;
    codUserInserim?: string;
    dAggiorn?: Date;
    dInserim?: Date;
    flgSospensioniInCorso?: string;
    id?: number;
    idProspetto?: number;
    numCatProtInForza?: number;
    numCatProtInForzaCntDis?: number;
    numDisabiliInForza?: number;
    numLavoratoriBaseComputo?: number;
    numLavoratoriSospensione?: number;
    numPosizioniEsonerate?: number;
    numScopertCatProtReali?: number;
    numScopertCategorieProtette?: number;
    numScopertDisabili?: number;
    numScopertDisabiliReali?: number;
    quotaEsuberiArt18?: number;
    quotaRiservaArt18?: number;
    quotaRiservaDisabili?: number;
}
