/*
* SPDX-FileCopyrightText: Copyright 2022 | Regione Piemonte
* SPDX-License-Identifier: EUPL-1.2
*/
/**
 * Prodis
 * API per il backend della suite di Prodis.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface VistaElencoProvQ2 { 
    id?: number;
    convenzione?: string;
    dsProTProvincia?: string;
    dsTarga?: string;
    idProspetto?: number;
    idTProvincia?: number;
    numAssunzioniEffDopoTrasf?: number;
    numCateProtForza?: number;
    numCateProtForzaA17012000?: number;
    numCentralTelefoNonvedenti?: number;
    numConvenzioni12bis14Ft?: number;
    numDisabiliInForza?: number;
    numIntermittenti?: number;
    numLavAppartartCategArt18?: number;
    numLavAppartartCategoria?: number;
    numPartTime?: number;
    numPostiDisp?: number;
    numSomministratiFt?: number;
    numTelelavoroFt?: number;
    numTerariabMassofisNonved?: number;
    numTotaleLavoratDipendenti?: number;
    sospInCorso?: string;
    ptIntermittenti?: number;
    disabiliTempoPienoFt?: number;
    teleLavCatEscluseDisab?: number;
    flgConfermatoQ2?: string;
    numLavoratoriEsonero?: number;
}
